import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Home(),
          Image.asset('assets/images/my_image.png'),
        ]),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 801,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: Colors.white,
            boxShadow: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 11,
                top: 361,
                child: Container(
                  width: 659,
                  height: 345,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 9,
                        top: 44,
                        child: Container(
                          width: 316,
                          height: 301,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 316,
                                  height: 238,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: AssetImage('assets/images/my_image.png'),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(16),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 255,
                                child: Text(
                                  '위치 이름',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w400,
                                    height: 0.08,
                                    letterSpacing: -0.41,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 279,
                                child: Text(
                                  '경로 상세 정보',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                    letterSpacing: -0.41,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 230,
                                top: 255,
                                child: Container(
                                  width: 86,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 11),
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFF020202)),
                                      borderRadius: BorderRadius.circular(7),
                                    ),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.end,
                                    children: [
                                      Text(
                                        '시작하기',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Color(0xFF020202),
                                          fontSize: 15,
                                          fontFamily: 'Roboto',
                                          fontWeight: FontWeight.w400,
                                          height: 0.08,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 343,
                        top: 44,
                        child: Container(
                          width: 316,
                          height: 301,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 316,
                                  height: 238,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/316x238"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(16),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 255,
                                child: Text(
                                  '위치 이름',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 17,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w400,
                                    height: 0.08,
                                    letterSpacing: -0.41,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 279,
                                child: Text(
                                  '경로 상세 정보',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w400,
                                    height: 0.11,
                                    letterSpacing: -0.41,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 230,
                                top: 255,
                                child: Container(
                                  width: 86,
                                  height: 40,
                                  padding: const EdgeInsets.symmetric(horizontal: 15, vertical: 11),
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(width: 1, color: Color(0xFF020202)),
                                      borderRadius: BorderRadius.circular(7),
                                    ),
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.end,
                                    children: [
                                      Text(
                                        '시작하기',
                                        textAlign: TextAlign.center,
                                        style: TextStyle(
                                          color: Color(0xFF020202),
                                          fontSize: 15,
                                          fontFamily: 'Roboto',
                                          fontWeight: FontWeight.w400,
                                          height: 0.08,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 375,
                          height: 44,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 375,
                                  padding: const EdgeInsets.only(
                                    top: 11,
                                    left: 15,
                                    right: 244,
                                    bottom: 11,
                                  ),
                                  decoration: BoxDecoration(color: Colors.white),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Text(
                                        '오늘의 경로 추천',
                                        style: TextStyle(
                                          color: Color(0xFF020202),
                                          fontSize: 17,
                                          fontFamily: 'SF Pro Text',
                                          fontWeight: FontWeight.w400,
                                          height: 0.08,
                                          letterSpacing: -0.41,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 313,
                                top: 11,
                                child: Text(
                                  '더보기',
                                  textAlign: TextAlign.right,
                                  style: TextStyle(
                                    color: Color(0xFFBDBDBD),
                                    fontSize: 17,
                                    fontFamily: 'SF Pro Text',
                                    fontWeight: FontWeight.w400,
                                    height: 0.08,
                                    letterSpacing: -0.41,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 163,
                child: Container(
                  width: 358,
                  height: 183,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 358,
                          height: 183,
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.00, 1.00),
                              end: Alignment(0, -1),
                              colors: [Color(0xFFF94444), Color(0xFFF47072)],
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(27),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 307,
                        top: 12,
                        child: Container(
                          width: 34,
                          height: 34,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 34,
                                  height: 34,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 17,
                                top: 9,
                                child: Text(
                                  'I',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF2B2B2B),
                                    fontSize: 16,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 0.06,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10,
                                top: 9,
                                child: Text(
                                  'I',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Color(0xFF2B2B2B),
                                    fontSize: 16,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 0.06,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 80,
                        top: 133,
                        child: Container(
                          width: 206,
                          height: 34,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 92,
                                  height: 34,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 28.88,
                                        top: 9.09,
                                        child: SizedBox(
                                          width: 32.09,
                                          height: 11.83,
                                          child: Text(
                                            '10.9',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Color(0xFF2B2B2B),
                                              fontSize: 14,
                                              fontFamily: 'Noto Sans KR',
                                              fontWeight: FontWeight.w700,
                                              height: 0.08,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 63.12,
                                        top: 11.30,
                                        child: SizedBox(
                                          width: 12.84,
                                          height: 11.83,
                                          child: Text(
                                            'KM',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Color(0xFFA3A3A3),
                                              fontSize: 8,
                                              fontFamily: 'Noto Sans KR',
                                              fontWeight: FontWeight.w500,
                                              height: 0.25,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.63,
                                        top: 9.09,
                                        child: SizedBox(
                                          width: 14.98,
                                          height: 11.83,
                                          child: Text(
                                            '👟',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 14,
                                              fontFamily: 'Noto Sans KR',
                                              fontWeight: FontWeight.w700,
                                              height: 0.08,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 114,
                                top: 0,
                                child: Container(
                                  width: 92,
                                  height: 34,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 24,
                                        top: 9,
                                        child: SizedBox(
                                          width: 40,
                                          height: 12,
                                          child: Text(
                                            '3432',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Color(0xFF2B2B2B),
                                              fontSize: 14,
                                              fontFamily: 'Noto Sans KR',
                                              fontWeight: FontWeight.w700,
                                              height: 0.08,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 63,
                                        top: 11,
                                        child: SizedBox(
                                          width: 25,
                                          height: 12,
                                          child: Text(
                                            '걸음수',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Color(0xFFA3A3A3),
                                              fontSize: 8,
                                              fontFamily: 'Noto Sans KR',
                                              fontWeight: FontWeight.w500,
                                              height: 0.25,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.63,
                                        top: 9.09,
                                        child: SizedBox(
                                          width: 14.98,
                                          height: 11.83,
                                          child: Text(
                                            '👣',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 14,
                                              fontFamily: 'Noto Sans KR',
                                              fontWeight: FontWeight.w700,
                                              height: 0.08,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        top: 16,
                        child: Container(
                          width: 117,
                          height: 29,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 25,
                                top: 0,
                                child: Text.rich(
                                  TextSpan(
                                    children: [
                                      TextSpan(
                                        text: '️',
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 30,
                                          fontFamily: 'Noto Sans KR',
                                          fontWeight: FontWeight.w700,
                                          height: 0.02,
                                        ),
                                      ),
                                      TextSpan(
                                        text: '마포대교',
                                        style: TextStyle(
                                          color: Colors.white,
                                          fontSize: 25,
                                          fontFamily: 'Noto Sans KR',
                                          fontWeight: FontWeight.w700,
                                          height: 0.01,
                                        ),
                                      ),
                                    ],
                                  ),
                                  textAlign: TextAlign.center,
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 3,
                                child: SizedBox(
                                  width: 16,
                                  height: 26,
                                  child: Text(
                                    '🏃',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 30,
                                      fontFamily: 'Noto Sans KR',
                                      fontWeight: FontWeight.w700,
                                      height: 0.02,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 116,
                        top: 65,
                        child: Text(
                          '01 : 04 : 57',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFF2B2B2B),
                            fontSize: 24,
                            fontFamily: 'Noto Sans KR',
                            fontWeight: FontWeight.w700,
                            height: 0.03,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 113,
                        top: 97,
                        child: Text.rich(
                          TextSpan(
                            children: [
                              TextSpan(
                                text: '7',
                                style: TextStyle(
                                  color: Color(0xFF877DFF),
                                  fontSize: 12,
                                  fontFamily: 'Noto Sans KR',
                                  fontWeight: FontWeight.w700,
                                  height: 0.11,
                                ),
                              ),
                              TextSpan(
                                text: '명이 함께 달리고 있어요!',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 12,
                                  fontFamily: 'Noto Sans KR',
                                  fontWeight: FontWeight.w700,
                                  height: 0.11,
                                ),
                              ),
                            ],
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 123,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: '홍길동',
                        style: TextStyle(
                          color: Color(0xFFFF6363),
                          fontSize: 25,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w700,
                          height: 0.03,
                        ),
                      ),
                      TextSpan(
                        text: ' ',
                        style: TextStyle(
                          color: Color(0xFF93D8D8),
                          fontSize: 25,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w700,
                          height: 0.03,
                        ),
                      ),
                      TextSpan(
                        text: '님 RUNNING PLACE',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 20,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w500,
                          height: 0.04,
                        ),
                      ),
                    ],
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  height: 97,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 375,
                        height: 44,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Colors.white),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 32,
                              top: 13,
                              child: Text(
                                '9:41',
                                style: TextStyle(
                                  color: Color(0xFF020202),
                                  fontSize: 15,
                                  fontFamily: 'SF Pro Text',
                                  fontWeight: FontWeight.w600,
                                  height: 0.09,
                                  letterSpacing: -0.32,
                                ),
                              ),
                            ),
                            Positioned(
                              left: 295,
                              top: 15,
                              child: Container(
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 20,
                                      height: 16,
                                      padding: const EdgeInsets.only(
                                        top: 3,
                                        left: 1,
                                        right: 2,
                                        bottom: 2.33,
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 17,
                                            height: 10.67,
                                            decoration: BoxDecoration(
                                              image: DecorationImage(
                                                image: NetworkImage("https://via.placeholder.com/17x11"),
                                                fit: BoxFit.fill,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 16,
                                      height: 16,
                                      padding: const EdgeInsets.only(
                                        top: 3,
                                        left: 0.35,
                                        right: 0.38,
                                        bottom: 2.03,
                                      ),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 15.27,
                                            height: 10.97,
                                            decoration: BoxDecoration(
                                              image: DecorationImage(
                                                image: NetworkImage("https://via.placeholder.com/15x11"),
                                                fit: BoxFit.fill,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      width: 25,
                                      height: 16,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(children: [
                                          ]),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 375,
                        height: 52,
                        padding: const EdgeInsets.only(
                          top: 1,
                          left: 16,
                          right: 16,
                          bottom: 10,
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            SizedBox(
                              width: 343,
                              child: Text(
                                'Home',
                                style: TextStyle(
                                  color: Color(0xFF020202),
                                  fontSize: 34,
                                  fontFamily: 'SF Pro Display',
                                  fontWeight: FontWeight.w700,
                                  height: 0.04,
                                  letterSpacing: 0.37,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: double.infinity,
                        height: 1,
                        decoration: BoxDecoration(color: Color(0xFF020202)),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -2,
                top: 714,
                child: Container(
                  width: 390,
                  height: 91,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 375,
                        height: 53,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(color: Colors.white),
                        child: Stack(
                          children: [
                            Positioned(
                              left: 28,
                              top: 1,
                              child: Container(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 36,
                                      height: 36,
                                      padding: const EdgeInsets.all(8),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 20,
                                            height: 20,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 2, color: Color(0xFF424242)),
                                                borderRadius: BorderRadius.circular(6),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      'Home',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF212121),
                                        fontSize: 10,
                                        fontFamily: 'SF Pro Text',
                                        fontWeight: FontWeight.w700,
                                        height: 0,
                                        letterSpacing: -0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 122,
                              top: 1,
                              child: Container(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 36,
                                      height: 36,
                                      padding: const EdgeInsets.all(8),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 20,
                                            height: 20,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 2, color: Color(0xFF424242)),
                                                borderRadius: BorderRadius.circular(6),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      'Route',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF212121),
                                        fontSize: 10,
                                        fontFamily: 'SF Pro Text',
                                        fontWeight: FontWeight.w500,
                                        height: 0,
                                        letterSpacing: -0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 216,
                              top: 1,
                              child: Container(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 36,
                                      height: 36,
                                      padding: const EdgeInsets.all(8),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 20,
                                            height: 20,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 2, color: Color(0xFF424242)),
                                                borderRadius: BorderRadius.circular(6),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      'Match',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF212121),
                                        fontSize: 10,
                                        fontFamily: 'SF Pro Text',
                                        fontWeight: FontWeight.w500,
                                        height: 0,
                                        letterSpacing: -0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 310,
                              top: 1,
                              child: Container(
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Container(
                                      width: 36,
                                      height: 36,
                                      padding: const EdgeInsets.all(8),
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.center,
                                        children: [
                                          Container(
                                            width: 20,
                                            height: 20,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 2, color: Color(0xFF424242)),
                                                borderRadius: BorderRadius.circular(6),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Text(
                                      'MyPage',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF212121),
                                        fontSize: 10,
                                        fontFamily: 'SF Pro Text',
                                        fontWeight: FontWeight.w500,
                                        height: 0,
                                        letterSpacing: -0.24,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 375,
                                height: 1,
                                decoration: BoxDecoration(color: Color(0xFF020202)),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 375,
                        height: 34,
                        padding: const EdgeInsets.only(
                          top: 21,
                          left: 121,
                          right: 120,
                          bottom: 8,
                        ),
                        decoration: BoxDecoration(color: Colors.white),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 134,
                              height: 5,
                              decoration: ShapeDecoration(
                                color: Color(0xFF020202),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(100),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}